pipeline {
    agent any
    stages {
        stage('Deploy and Install') {
            steps {
                // Jenkins tells the ubuntu user to pull the latest code and install dependencies
                sh '''
                sudo -u ubuntu bash -c "cd /home/ubuntu/<your-flask-folder-name> && git pull origin main && source venv/bin/activate && pip install -r requirements.txt"
                '''
            }
        }
        stage('Restart Backend') {
            steps {
                // Jenkins tells the ubuntu user to restart PM2
                sh 'sudo -u ubuntu pm2 restart flask-backend'
            }
        }
    }
}